package com.lql.graduation.mapper;

import com.lql.graduation.pojo.DeviceTimer;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DeviceTimerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deviceTimerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    int insert(DeviceTimer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    int insertSelective(DeviceTimer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    DeviceTimer selectByPrimaryKey(String deviceTimerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceTimer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_TIMER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceTimer record);

    List<DeviceTimer> queryDeviceTimerByStatus(Integer status);
}