package com.lql.graduation.mapper;

import com.lql.graduation.pojo.DeviceAlert;
import org.springframework.stereotype.Repository;

@Repository
public interface DeviceAlertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deviceAlertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    int insert(DeviceAlert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    int insertSelective(DeviceAlert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    DeviceAlert selectByPrimaryKey(String deviceAlertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceAlert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ALERT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceAlert record);
}