package com.lql.graduation.mapper;

import com.lql.graduation.pojo.DeviceInterface;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DeviceInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deviceInterfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    int insert(DeviceInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    int insertSelective(DeviceInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    DeviceInterface selectByPrimaryKey(String deviceInterfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_INTERFACE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceInterface record);

    List<DeviceInterface> selectByStatus(Integer status);

    int selectDeviceInterfaceCount();
}