package com.lql.graduation.pojo;

import java.util.Date;

public class DeviceInterface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    private String deviceInterfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    private String devDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_ID
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_INTERFACE_NAME
     *
     * @mbg.generated
     */
    private String deviceInterfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_INTERFACE_TYPE
     *
     * @mbg.generated
     */
    private Integer deviceInterfaceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_UNIT
     *
     * @mbg.generated
     */
    private String deviceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_INTEFACE_DES
     *
     * @mbg.generated
     */
    private String deviceIntefaceDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.DEVICE_INTERFACE_STATUS
     *
     * @mbg.generated
     */
    private String deviceInterfaceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_INTERFACE.UPDATE_TIMER
     *
     * @mbg.generated
     */
    private Date updateTimer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_ID
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    public String getDeviceInterfaceId() {
        return deviceInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_ID
     *
     * @param deviceInterfaceId the value for DEVICE_INTERFACE.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    public void setDeviceInterfaceId(String deviceInterfaceId) {
        this.deviceInterfaceId = deviceInterfaceId == null ? null : deviceInterfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEV_DEVICE_ID
     *
     * @return the value of DEVICE_INTERFACE.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    public String getDevDeviceId() {
        return devDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEV_DEVICE_ID
     *
     * @param devDeviceId the value for DEVICE_INTERFACE.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    public void setDevDeviceId(String devDeviceId) {
        this.devDeviceId = devDeviceId == null ? null : devDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_ID
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_ID
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_ID
     *
     * @param deviceId the value for DEVICE_INTERFACE.DEVICE_ID
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_NAME
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_INTERFACE_NAME
     *
     * @mbg.generated
     */
    public String getDeviceInterfaceName() {
        return deviceInterfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_NAME
     *
     * @param deviceInterfaceName the value for DEVICE_INTERFACE.DEVICE_INTERFACE_NAME
     *
     * @mbg.generated
     */
    public void setDeviceInterfaceName(String deviceInterfaceName) {
        this.deviceInterfaceName = deviceInterfaceName == null ? null : deviceInterfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_TYPE
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_INTERFACE_TYPE
     *
     * @mbg.generated
     */
    public Integer getDeviceInterfaceType() {
        return deviceInterfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_TYPE
     *
     * @param deviceInterfaceType the value for DEVICE_INTERFACE.DEVICE_INTERFACE_TYPE
     *
     * @mbg.generated
     */
    public void setDeviceInterfaceType(Integer deviceInterfaceType) {
        this.deviceInterfaceType = deviceInterfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_UNIT
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_UNIT
     *
     * @mbg.generated
     */
    public String getDeviceUnit() {
        return deviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_UNIT
     *
     * @param deviceUnit the value for DEVICE_INTERFACE.DEVICE_UNIT
     *
     * @mbg.generated
     */
    public void setDeviceUnit(String deviceUnit) {
        this.deviceUnit = deviceUnit == null ? null : deviceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_INTEFACE_DES
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_INTEFACE_DES
     *
     * @mbg.generated
     */
    public String getDeviceIntefaceDes() {
        return deviceIntefaceDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_INTEFACE_DES
     *
     * @param deviceIntefaceDes the value for DEVICE_INTERFACE.DEVICE_INTEFACE_DES
     *
     * @mbg.generated
     */
    public void setDeviceIntefaceDes(String deviceIntefaceDes) {
        this.deviceIntefaceDes = deviceIntefaceDes == null ? null : deviceIntefaceDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_STATUS
     *
     * @return the value of DEVICE_INTERFACE.DEVICE_INTERFACE_STATUS
     *
     * @mbg.generated
     */
    public String getDeviceInterfaceStatus() {
        return deviceInterfaceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.DEVICE_INTERFACE_STATUS
     *
     * @param deviceInterfaceStatus the value for DEVICE_INTERFACE.DEVICE_INTERFACE_STATUS
     *
     * @mbg.generated
     */
    public void setDeviceInterfaceStatus(String deviceInterfaceStatus) {
        this.deviceInterfaceStatus = deviceInterfaceStatus == null ? null : deviceInterfaceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.CREATE_BY
     *
     * @return the value of DEVICE_INTERFACE.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.CREATE_BY
     *
     * @param createBy the value for DEVICE_INTERFACE.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.CREATE_TIME
     *
     * @return the value of DEVICE_INTERFACE.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.CREATE_TIME
     *
     * @param createTime the value for DEVICE_INTERFACE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.UPDATE_BY
     *
     * @return the value of DEVICE_INTERFACE.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.UPDATE_BY
     *
     * @param updateBy the value for DEVICE_INTERFACE.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_INTERFACE.UPDATE_TIMER
     *
     * @return the value of DEVICE_INTERFACE.UPDATE_TIMER
     *
     * @mbg.generated
     */
    public Date getUpdateTimer() {
        return updateTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_INTERFACE.UPDATE_TIMER
     *
     * @param updateTimer the value for DEVICE_INTERFACE.UPDATE_TIMER
     *
     * @mbg.generated
     */
    public void setUpdateTimer(Date updateTimer) {
        this.updateTimer = updateTimer;
    }
}