package com.lql.graduation.pojo;

import java.util.Date;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_ID
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_NAME
     *
     * @mbg.generated
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.APIKEY
     *
     * @mbg.generated
     */
    private String apikey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_ISPUBLIC
     *
     * @mbg.generated
     */
    private String deviceIspublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_ISONLINE
     *
     * @mbg.generated
     */
    private Integer deviceIsonline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_TIME
     *
     * @mbg.generated
     */
    private Integer deviceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.DEVICE_STATUE
     *
     * @mbg.generated
     */
    private Integer deviceStatue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.CRATE_BY
     *
     * @mbg.generated
     */
    private String crateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.CREAT_TIME
     *
     * @mbg.generated
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_ID
     *
     * @return the value of DEVICE.DEVICE_ID
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_ID
     *
     * @param deviceId the value for DEVICE.DEVICE_ID
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.USER_ID
     *
     * @return the value of DEVICE.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.USER_ID
     *
     * @param userId the value for DEVICE.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_NAME
     *
     * @return the value of DEVICE.DEVICE_NAME
     *
     * @mbg.generated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_NAME
     *
     * @param deviceName the value for DEVICE.DEVICE_NAME
     *
     * @mbg.generated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.APIKEY
     *
     * @return the value of DEVICE.APIKEY
     *
     * @mbg.generated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.APIKEY
     *
     * @param apikey the value for DEVICE.APIKEY
     *
     * @mbg.generated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_ISPUBLIC
     *
     * @return the value of DEVICE.DEVICE_ISPUBLIC
     *
     * @mbg.generated
     */
    public String getDeviceIspublic() {
        return deviceIspublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_ISPUBLIC
     *
     * @param deviceIspublic the value for DEVICE.DEVICE_ISPUBLIC
     *
     * @mbg.generated
     */
    public void setDeviceIspublic(String deviceIspublic) {
        this.deviceIspublic = deviceIspublic == null ? null : deviceIspublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_ISONLINE
     *
     * @return the value of DEVICE.DEVICE_ISONLINE
     *
     * @mbg.generated
     */
    public Integer getDeviceIsonline() {
        return deviceIsonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_ISONLINE
     *
     * @param deviceIsonline the value for DEVICE.DEVICE_ISONLINE
     *
     * @mbg.generated
     */
    public void setDeviceIsonline(Integer deviceIsonline) {
        this.deviceIsonline = deviceIsonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_TIME
     *
     * @return the value of DEVICE.DEVICE_TIME
     *
     * @mbg.generated
     */
    public Integer getDeviceTime() {
        return deviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_TIME
     *
     * @param deviceTime the value for DEVICE.DEVICE_TIME
     *
     * @mbg.generated
     */
    public void setDeviceTime(Integer deviceTime) {
        this.deviceTime = deviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.DEVICE_STATUE
     *
     * @return the value of DEVICE.DEVICE_STATUE
     *
     * @mbg.generated
     */
    public Integer getDeviceStatue() {
        return deviceStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.DEVICE_STATUE
     *
     * @param deviceStatue the value for DEVICE.DEVICE_STATUE
     *
     * @mbg.generated
     */
    public void setDeviceStatue(Integer deviceStatue) {
        this.deviceStatue = deviceStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.CRATE_BY
     *
     * @return the value of DEVICE.CRATE_BY
     *
     * @mbg.generated
     */
    public String getCrateBy() {
        return crateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.CRATE_BY
     *
     * @param crateBy the value for DEVICE.CRATE_BY
     *
     * @mbg.generated
     */
    public void setCrateBy(String crateBy) {
        this.crateBy = crateBy == null ? null : crateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.CREAT_TIME
     *
     * @return the value of DEVICE.CREAT_TIME
     *
     * @mbg.generated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.CREAT_TIME
     *
     * @param creatTime the value for DEVICE.CREAT_TIME
     *
     * @mbg.generated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.UPDATE_BY
     *
     * @return the value of DEVICE.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.UPDATE_BY
     *
     * @param updateBy the value for DEVICE.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.UPDATE_TIME
     *
     * @return the value of DEVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.UPDATE_TIME
     *
     * @param updateTime the value for DEVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}