package com.lql.graduation.pojo;

import java.util.Date;

public class Devicecon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.DEVICECON_ID
     *
     * @mbg.generated
     */
    private String deviceconId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.TODEVICE_ID
     *
     * @mbg.generated
     */
    private String todeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.DEVICEDON_MESSAGE
     *
     * @mbg.generated
     */
    private String devicedonMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.CRAETE_TIME
     *
     * @mbg.generated
     */
    private Date craeteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICECON.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.DEVICECON_ID
     *
     * @return the value of DEVICECON.DEVICECON_ID
     *
     * @mbg.generated
     */
    public String getDeviceconId() {
        return deviceconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.DEVICECON_ID
     *
     * @param deviceconId the value for DEVICECON.DEVICECON_ID
     *
     * @mbg.generated
     */
    public void setDeviceconId(String deviceconId) {
        this.deviceconId = deviceconId == null ? null : deviceconId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.TODEVICE_ID
     *
     * @return the value of DEVICECON.TODEVICE_ID
     *
     * @mbg.generated
     */
    public String getTodeviceId() {
        return todeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.TODEVICE_ID
     *
     * @param todeviceId the value for DEVICECON.TODEVICE_ID
     *
     * @mbg.generated
     */
    public void setTodeviceId(String todeviceId) {
        this.todeviceId = todeviceId == null ? null : todeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.DEVICEDON_MESSAGE
     *
     * @return the value of DEVICECON.DEVICEDON_MESSAGE
     *
     * @mbg.generated
     */
    public String getDevicedonMessage() {
        return devicedonMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.DEVICEDON_MESSAGE
     *
     * @param devicedonMessage the value for DEVICECON.DEVICEDON_MESSAGE
     *
     * @mbg.generated
     */
    public void setDevicedonMessage(String devicedonMessage) {
        this.devicedonMessage = devicedonMessage == null ? null : devicedonMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.CREATE_BY
     *
     * @return the value of DEVICECON.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.CREATE_BY
     *
     * @param createBy the value for DEVICECON.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.CRAETE_TIME
     *
     * @return the value of DEVICECON.CRAETE_TIME
     *
     * @mbg.generated
     */
    public Date getCraeteTime() {
        return craeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.CRAETE_TIME
     *
     * @param craeteTime the value for DEVICECON.CRAETE_TIME
     *
     * @mbg.generated
     */
    public void setCraeteTime(Date craeteTime) {
        this.craeteTime = craeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.UPDATE_BY
     *
     * @return the value of DEVICECON.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.UPDATE_BY
     *
     * @param updateBy the value for DEVICECON.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICECON.UPDATE_TIME
     *
     * @return the value of DEVICECON.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICECON.UPDATE_TIME
     *
     * @param updateTime the value for DEVICECON.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}