package com.lql.graduation.pojo;

import java.util.Date;

public class DeviceTimer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_ID
     *
     * @mbg.generated
     */
    private String deviceTimerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    private String devDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_ID
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_NAME
     *
     * @mbg.generated
     */
    private String deviceTimerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_TODE
     *
     * @mbg.generated
     */
    private String deviceTimerTode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIEMR_WEEK
     *
     * @mbg.generated
     */
    private Integer deviceTiemrWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIEMR_HOUR
     *
     * @mbg.generated
     */
    private Integer deviceTiemrHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_MINER
     *
     * @mbg.generated
     */
    private Integer deviceTimerMiner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_MES
     *
     * @mbg.generated
     */
    private String deviceTimerMes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.DEVICE_TIMER_STATUS
     *
     * @mbg.generated
     */
    private Integer deviceTimerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_TIMER.UPDATE_TIMER
     *
     * @mbg.generated
     */
    private Date updateTimer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_ID
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_ID
     *
     * @mbg.generated
     */
    public String getDeviceTimerId() {
        return deviceTimerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_ID
     *
     * @param deviceTimerId the value for DEVICE_TIMER.DEVICE_TIMER_ID
     *
     * @mbg.generated
     */
    public void setDeviceTimerId(String deviceTimerId) {
        this.deviceTimerId = deviceTimerId == null ? null : deviceTimerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEV_DEVICE_ID
     *
     * @return the value of DEVICE_TIMER.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    public String getDevDeviceId() {
        return devDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEV_DEVICE_ID
     *
     * @param devDeviceId the value for DEVICE_TIMER.DEV_DEVICE_ID
     *
     * @mbg.generated
     */
    public void setDevDeviceId(String devDeviceId) {
        this.devDeviceId = devDeviceId == null ? null : devDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_ID
     *
     * @return the value of DEVICE_TIMER.DEVICE_ID
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_ID
     *
     * @param deviceId the value for DEVICE_TIMER.DEVICE_ID
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_NAME
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_NAME
     *
     * @mbg.generated
     */
    public String getDeviceTimerName() {
        return deviceTimerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_NAME
     *
     * @param deviceTimerName the value for DEVICE_TIMER.DEVICE_TIMER_NAME
     *
     * @mbg.generated
     */
    public void setDeviceTimerName(String deviceTimerName) {
        this.deviceTimerName = deviceTimerName == null ? null : deviceTimerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_TODE
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_TODE
     *
     * @mbg.generated
     */
    public String getDeviceTimerTode() {
        return deviceTimerTode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_TODE
     *
     * @param deviceTimerTode the value for DEVICE_TIMER.DEVICE_TIMER_TODE
     *
     * @mbg.generated
     */
    public void setDeviceTimerTode(String deviceTimerTode) {
        this.deviceTimerTode = deviceTimerTode == null ? null : deviceTimerTode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIEMR_WEEK
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIEMR_WEEK
     *
     * @mbg.generated
     */
    public Integer getDeviceTiemrWeek() {
        return deviceTiemrWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIEMR_WEEK
     *
     * @param deviceTiemrWeek the value for DEVICE_TIMER.DEVICE_TIEMR_WEEK
     *
     * @mbg.generated
     */
    public void setDeviceTiemrWeek(Integer deviceTiemrWeek) {
        this.deviceTiemrWeek = deviceTiemrWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIEMR_HOUR
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIEMR_HOUR
     *
     * @mbg.generated
     */
    public Integer getDeviceTiemrHour() {
        return deviceTiemrHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIEMR_HOUR
     *
     * @param deviceTiemrHour the value for DEVICE_TIMER.DEVICE_TIEMR_HOUR
     *
     * @mbg.generated
     */
    public void setDeviceTiemrHour(Integer deviceTiemrHour) {
        this.deviceTiemrHour = deviceTiemrHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_MINER
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_MINER
     *
     * @mbg.generated
     */
    public Integer getDeviceTimerMiner() {
        return deviceTimerMiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_MINER
     *
     * @param deviceTimerMiner the value for DEVICE_TIMER.DEVICE_TIMER_MINER
     *
     * @mbg.generated
     */
    public void setDeviceTimerMiner(Integer deviceTimerMiner) {
        this.deviceTimerMiner = deviceTimerMiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_MES
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_MES
     *
     * @mbg.generated
     */
    public String getDeviceTimerMes() {
        return deviceTimerMes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_MES
     *
     * @param deviceTimerMes the value for DEVICE_TIMER.DEVICE_TIMER_MES
     *
     * @mbg.generated
     */
    public void setDeviceTimerMes(String deviceTimerMes) {
        this.deviceTimerMes = deviceTimerMes == null ? null : deviceTimerMes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.DEVICE_TIMER_STATUS
     *
     * @return the value of DEVICE_TIMER.DEVICE_TIMER_STATUS
     *
     * @mbg.generated
     */
    public Integer getDeviceTimerStatus() {
        return deviceTimerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.DEVICE_TIMER_STATUS
     *
     * @param deviceTimerStatus the value for DEVICE_TIMER.DEVICE_TIMER_STATUS
     *
     * @mbg.generated
     */
    public void setDeviceTimerStatus(Integer deviceTimerStatus) {
        this.deviceTimerStatus = deviceTimerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.CREATE_BY
     *
     * @return the value of DEVICE_TIMER.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.CREATE_BY
     *
     * @param createBy the value for DEVICE_TIMER.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.CREATE_TIME
     *
     * @return the value of DEVICE_TIMER.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.CREATE_TIME
     *
     * @param createTime the value for DEVICE_TIMER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.UPDATE_BY
     *
     * @return the value of DEVICE_TIMER.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.UPDATE_BY
     *
     * @param updateBy the value for DEVICE_TIMER.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_TIMER.UPDATE_TIMER
     *
     * @return the value of DEVICE_TIMER.UPDATE_TIMER
     *
     * @mbg.generated
     */
    public Date getUpdateTimer() {
        return updateTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_TIMER.UPDATE_TIMER
     *
     * @param updateTimer the value for DEVICE_TIMER.UPDATE_TIMER
     *
     * @mbg.generated
     */
    public void setUpdateTimer(Date updateTimer) {
        this.updateTimer = updateTimer;
    }
}