package com.lql.graduation.pojo;

import java.util.Date;

public class DeviceAlert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_ALERT_ID
     *
     * @mbg.generated
     */
    private String deviceAlertId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_ALERT_NAME
     *
     * @mbg.generated
     */
    private String deviceAlertName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_ALERT_STATUS
     *
     * @mbg.generated
     */
    private String deviceAlertStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    private String deviceInterfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_ALERT_VAL
     *
     * @mbg.generated
     */
    private String deviceAlertVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.DEVICE_ALERT_SENDMETHOD
     *
     * @mbg.generated
     */
    private Integer deviceAlertSendmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE_ALERT.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_ALERT_ID
     *
     * @return the value of DEVICE_ALERT.DEVICE_ALERT_ID
     *
     * @mbg.generated
     */
    public String getDeviceAlertId() {
        return deviceAlertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_ALERT_ID
     *
     * @param deviceAlertId the value for DEVICE_ALERT.DEVICE_ALERT_ID
     *
     * @mbg.generated
     */
    public void setDeviceAlertId(String deviceAlertId) {
        this.deviceAlertId = deviceAlertId == null ? null : deviceAlertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_ALERT_NAME
     *
     * @return the value of DEVICE_ALERT.DEVICE_ALERT_NAME
     *
     * @mbg.generated
     */
    public String getDeviceAlertName() {
        return deviceAlertName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_ALERT_NAME
     *
     * @param deviceAlertName the value for DEVICE_ALERT.DEVICE_ALERT_NAME
     *
     * @mbg.generated
     */
    public void setDeviceAlertName(String deviceAlertName) {
        this.deviceAlertName = deviceAlertName == null ? null : deviceAlertName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_ALERT_STATUS
     *
     * @return the value of DEVICE_ALERT.DEVICE_ALERT_STATUS
     *
     * @mbg.generated
     */
    public String getDeviceAlertStatus() {
        return deviceAlertStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_ALERT_STATUS
     *
     * @param deviceAlertStatus the value for DEVICE_ALERT.DEVICE_ALERT_STATUS
     *
     * @mbg.generated
     */
    public void setDeviceAlertStatus(String deviceAlertStatus) {
        this.deviceAlertStatus = deviceAlertStatus == null ? null : deviceAlertStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_INTERFACE_ID
     *
     * @return the value of DEVICE_ALERT.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    public String getDeviceInterfaceId() {
        return deviceInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_INTERFACE_ID
     *
     * @param deviceInterfaceId the value for DEVICE_ALERT.DEVICE_INTERFACE_ID
     *
     * @mbg.generated
     */
    public void setDeviceInterfaceId(String deviceInterfaceId) {
        this.deviceInterfaceId = deviceInterfaceId == null ? null : deviceInterfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_ALERT_VAL
     *
     * @return the value of DEVICE_ALERT.DEVICE_ALERT_VAL
     *
     * @mbg.generated
     */
    public String getDeviceAlertVal() {
        return deviceAlertVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_ALERT_VAL
     *
     * @param deviceAlertVal the value for DEVICE_ALERT.DEVICE_ALERT_VAL
     *
     * @mbg.generated
     */
    public void setDeviceAlertVal(String deviceAlertVal) {
        this.deviceAlertVal = deviceAlertVal == null ? null : deviceAlertVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.DEVICE_ALERT_SENDMETHOD
     *
     * @return the value of DEVICE_ALERT.DEVICE_ALERT_SENDMETHOD
     *
     * @mbg.generated
     */
    public Integer getDeviceAlertSendmethod() {
        return deviceAlertSendmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.DEVICE_ALERT_SENDMETHOD
     *
     * @param deviceAlertSendmethod the value for DEVICE_ALERT.DEVICE_ALERT_SENDMETHOD
     *
     * @mbg.generated
     */
    public void setDeviceAlertSendmethod(Integer deviceAlertSendmethod) {
        this.deviceAlertSendmethod = deviceAlertSendmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.CREATE_BY
     *
     * @return the value of DEVICE_ALERT.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.CREATE_BY
     *
     * @param createBy the value for DEVICE_ALERT.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.CREATE_TIME
     *
     * @return the value of DEVICE_ALERT.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.CREATE_TIME
     *
     * @param createTime the value for DEVICE_ALERT.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.UPDATE_BY
     *
     * @return the value of DEVICE_ALERT.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.UPDATE_BY
     *
     * @param updateBy the value for DEVICE_ALERT.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE_ALERT.UPDATE_TIME
     *
     * @return the value of DEVICE_ALERT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE_ALERT.UPDATE_TIME
     *
     * @param updateTime the value for DEVICE_ALERT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}